/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsOneclientRouteImport } from './routes/projects/oneclient'

const ProjectsOneclientRoute = ProjectsOneclientRouteImport.update({
  id: '/projects/oneclient',
  path: '/projects/oneclient',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/projects/oneclient': typeof ProjectsOneclientRoute
}
export interface FileRoutesByTo {
  '/projects/oneclient': typeof ProjectsOneclientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/projects/oneclient': typeof ProjectsOneclientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/projects/oneclient'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects/oneclient'
  id: '__root__' | '/projects/oneclient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProjectsOneclientRoute: typeof ProjectsOneclientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects/oneclient': {
      id: '/projects/oneclient'
      path: '/projects/oneclient'
      fullPath: '/projects/oneclient'
      preLoaderRoute: typeof ProjectsOneclientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProjectsOneclientRoute: ProjectsOneclientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
